
Parameters:
    BucketName:
        Type: String
        Default: dss-serverless

Resources:
    Bucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: PublicRead
            BucketName:
                Ref: BucketName
            WebsiteConfiguration:
                ErrorDocument: 404.html
                IndexDocument: index.html

    BucketPolicy:
        Type: AWS::S3::BucketPolicy
        DependsOn: Bucket
        Properties:
            Bucket: !Ref Bucket
            PolicyDocument:
                Statement:
                    Effect: Allow
                    Principal: '*'
                    Action: 's3:GetObject'
                    Resource: !Join 
                        - ''
                        - - 'arn:aws:s3:::'
                          - !Ref Bucket
                          - /*

Outputs:
    WebsiteURL:
        Value: !GetAtt 
            - Bucket
            - WebsiteURL
        Description: URL for website hosted on S3

